### ISSUE TITLE
Wrong singular form of "Taxes"

### ISSUE THREAD

**Issue by oSethoum** [mauroerta/deno-plural#4]
Am trying to use singular function to get the singular of the word "Taxes" but am getting "Taxe" instead of "Tax".

**Comment by mauroerta** [comment]
Hello @oSethoum, unfortunately I don't have a lot of time to fix this issue, if you can wait I'll work on it as soon as I can.
Anyway, If you already know how to fix this issue and you'll like to open a pull request you're welcome!
